# $FreeBSD$

PORTNAME=	pfSense-pkg-API
PORTVERSION=	0.0
PORTREVISION=	3
CATEGORIES=	sysutils
MASTER_SITES=	# empty
DISTFILES=	# empty
EXTRACT_ONLY=	# empty
MAINTAINER=	jaredhendrickson13@gmail.com
COMMENT=	pfSense API package
LICENSE=	APACHE20
NO_BUILD=	yes
NO_MTREE=	yes
SUB_FILES=	pkg-install pkg-deinstall
SUB_LIST=	PORTNAME=${PORTNAME}

do-extract:
	${MKDIR} ${WRKSRC}

do-intall:
	@echo "YES"


.include <bsd.port.mk>