# $FreeBSD$

PORTNAME=pfSense-pkg-API
PORTVERSION=1.1
PORTREVISION=1
CATEGORIES=sysutils
MASTER_SITES=# empty
DISTFILES=# empty
EXTRACT_ONLY=# empty
MAINTAINER=	jaredhendrickson13@gmail.com
COMMENT=pfSense API package
LICENSE=APACHE20
NO_BUILD=yes
NO_MTREE=yes
SUB_FILES=pkg-install pkg-deinstall
SUB_LIST=PORTNAME=${PORTNAME}

do-extract:
    ${MKDIR} ${WRKSRC}

do-install:
    {% for dir in files["dir"] -%}
    ${MKDIR} ${STAGEDIR}{{ dir }}
    {% endfor %}
    {% for file in files["file"] -%}
    ${INSTALL_DATA} ${FILESDIR}{{ file }} ${STAGEDIR}{{ file | dirname }}
    {% endfor %}
.include <bsd.port.mk>